/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.pedrodamata.calculadora.model.view;

import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author Pedro da Mata  <pescariaurbana@gmail.com>
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfPrimeiroNumero = new javax.swing.JTextField();
        tfSegundoNumero = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btSomar = new javax.swing.JButton();
        btSubtrair = new javax.swing.JButton();
        btMultiplicar = new javax.swing.JButton();
        btDividir = new javax.swing.JButton();
        btPotencia = new javax.swing.JButton();
        btRaiz = new javax.swing.JButton();
        btPercentagem = new javax.swing.JButton();
        btSeno = new javax.swing.JButton();
        btCoseno = new javax.swing.JButton();
        btTangente = new javax.swing.JButton();
        btArcoSeno = new javax.swing.JButton();
        btArcoCoseno = new javax.swing.JButton();
        btArcotangente = new javax.swing.JButton();
        btLog = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbResultado = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Primeiro número:");

        jLabel2.setBackground(new java.awt.Color(0, 51, 51));
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Segundo número:");

        tfPrimeiroNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPrimeiroNumeroActionPerformed(evt);
            }
        });

        tfSegundoNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSegundoNumeroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfPrimeiroNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                    .addComponent(tfSegundoNumero))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(tfPrimeiroNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfSegundoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));

        btSomar.setText("+");
        btSomar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSomarActionPerformed(evt);
            }
        });

        btSubtrair.setText("-");
        btSubtrair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSubtrairActionPerformed(evt);
            }
        });

        btMultiplicar.setText("x");
        btMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMultiplicarActionPerformed(evt);
            }
        });

        btDividir.setText(":");
        btDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDividirActionPerformed(evt);
            }
        });

        btPotencia.setText("xⁿ");
        btPotencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPotenciaActionPerformed(evt);
            }
        });

        btRaiz.setText("ˣ√y");
        btRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRaizActionPerformed(evt);
            }
        });

        btPercentagem.setText("%");
        btPercentagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPercentagemActionPerformed(evt);
            }
        });

        btSeno.setText("Sen");
        btSeno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSenoActionPerformed(evt);
            }
        });

        btCoseno.setText("Cos");
        btCoseno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCosenoActionPerformed(evt);
            }
        });

        btTangente.setText("Tan");
        btTangente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTangenteActionPerformed(evt);
            }
        });

        btArcoSeno.setText("ArcSen");
        btArcoSeno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btArcoSenoActionPerformed(evt);
            }
        });

        btArcoCoseno.setText("ArcCos");
        btArcoCoseno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btArcoCosenoActionPerformed(evt);
            }
        });

        btArcotangente.setText("ArcTan");
        btArcotangente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btArcotangenteActionPerformed(evt);
            }
        });

        btLog.setText("logᵧx");
        btLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btPotencia, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                    .addComponent(btCoseno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btSomar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btArcotangente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btTangente, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btArcoSeno, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btSubtrair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btMultiplicar, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                                    .addComponent(btPercentagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btSeno, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                            .addComponent(btArcoCoseno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btDividir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btLog, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSomar)
                    .addComponent(btMultiplicar)
                    .addComponent(btSubtrair)
                    .addComponent(btDividir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btPotencia)
                    .addComponent(btRaiz)
                    .addComponent(btPercentagem)
                    .addComponent(btSeno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCoseno)
                    .addComponent(btTangente)
                    .addComponent(btArcoSeno)
                    .addComponent(btArcoCoseno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btArcotangente)
                    .addComponent(btLog))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));

        jLabel3.setBackground(new java.awt.Color(0, 51, 51));
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("O resultado é:");

        lbResultado.setBackground(new java.awt.Color(0, 51, 51));
        lbResultado.setForeground(new java.awt.Color(0, 0, 0));
        lbResultado.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbResultado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbResultado))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfPrimeiroNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPrimeiroNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPrimeiroNumeroActionPerformed

    private void tfSegundoNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSegundoNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSegundoNumeroActionPerformed

    private void btSomarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSomarActionPerformed

        float num1 = Float.parseFloat(tfPrimeiroNumero.getText());
        float num2 = Float.parseFloat(tfSegundoNumero.getText());
        float resultado = num1 + num2;
        lbResultado.setText(String.valueOf(resultado));

        salvarOperacaoEmCSV("Soma", String.valueOf(num1), String.valueOf(num2), String.valueOf(resultado));

    }//GEN-LAST:event_btSomarActionPerformed

    private void btSubtrairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSubtrairActionPerformed
        float num1 = Float.parseFloat(tfPrimeiroNumero.getText());
        float num2 = Float.parseFloat(tfSegundoNumero.getText());
        float resultado = num1 - num2;
        lbResultado.setText(String.valueOf(resultado));

        salvarOperacaoEmCSV("Subtracao", String.valueOf(num1), String.valueOf(num2), String.valueOf(resultado));
    }//GEN-LAST:event_btSubtrairActionPerformed

    private void btMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMultiplicarActionPerformed
        float num1 = Float.parseFloat(tfPrimeiroNumero.getText());
        float num2 = Float.parseFloat(tfSegundoNumero.getText());
        float resultado = num1 * num2;
        lbResultado.setText(String.valueOf(resultado));

        salvarOperacaoEmCSV("Multiplicacao", String.valueOf(num1), String.valueOf(num2), String.valueOf(resultado));
    }//GEN-LAST:event_btMultiplicarActionPerformed

    private void btDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDividirActionPerformed
        float num1 = Float.parseFloat(tfPrimeiroNumero.getText());
        float num2 = Float.parseFloat(tfSegundoNumero.getText());

        if (num2 == 0) { 
            lbResultado.setText("Erro: Divisão por zero.");
            return;
        }

        float resultado = num1 / num2;
        lbResultado.setText(String.valueOf(resultado));

        salvarOperacaoEmCSV("Divisao", String.valueOf(num1), String.valueOf(num2), String.valueOf(resultado));
    }//GEN-LAST:event_btDividirActionPerformed

    private void btPotenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPotenciaActionPerformed
        float base = Float.parseFloat(tfPrimeiroNumero.getText());
        float expoente = Float.parseFloat(tfSegundoNumero.getText());
        double resultado = Math.pow(base, expoente);
        lbResultado.setText(String.valueOf(resultado));

        salvarOperacaoEmCSV("Potencia", String.valueOf(base), String.valueOf(expoente), String.valueOf(resultado));


    }//GEN-LAST:event_btPotenciaActionPerformed

    private void btRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRaizActionPerformed
        float radicandoY = Float.parseFloat(tfPrimeiroNumero.getText());
        float indiceRaizX = Float.parseFloat(tfSegundoNumero.getText());

        if (indiceRaizX == 0) {
            lbResultado.setText("Erro: Índice não pode ser zero.");
            return;
        }

        if (radicandoY < 0 && indiceRaizX % 2 == 0) {
            lbResultado.setText("Erro: Raiz par de negativo.");
            return;
        }

        double resultado = Math.pow(radicandoY, 1.0 / indiceRaizX);
        lbResultado.setText(String.valueOf(resultado));

        salvarOperacaoEmCSV("Raiz", String.valueOf(radicandoY), String.valueOf(indiceRaizX), String.valueOf(resultado));


    }//GEN-LAST:event_btRaizActionPerformed

    private void btPercentagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPercentagemActionPerformed
        float num1 = Float.parseFloat(tfPrimeiroNumero.getText());
        float num2 = Float.parseFloat(tfSegundoNumero.getText());
        float resultado = (num1 / 100) * num2;
        lbResultado.setText(String.valueOf(resultado));

        salvarOperacaoEmCSV("Porcentagem", String.valueOf(num1), String.valueOf(num2), String.valueOf(resultado));

    }//GEN-LAST:event_btPercentagemActionPerformed

    private void btSenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSenoActionPerformed
        float anguloGraus = Float.parseFloat(tfPrimeiroNumero.getText());
        double anguloRadianos = Math.toRadians(anguloGraus);
        double resultado = Math.sin(anguloRadianos);
        lbResultado.setText(String.valueOf(resultado));

        salvarOperacaoEmCSV("Seno", String.valueOf(anguloGraus), "", String.valueOf(resultado));
    }//GEN-LAST:event_btSenoActionPerformed

    private void btTangenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTangenteActionPerformed
        float angulo = Float.parseFloat(tfPrimeiroNumero.getText());
        if (Math.abs(angulo % 180 - 90) < 0.0001 || Math.abs(angulo % 180 + 90) < 0.0001) {
            lbResultado.setText("Erro: Tangente indefinida.");
            return;
        }

        double resultado = Math.tan(Math.toRadians(angulo));
        lbResultado.setText(String.valueOf(resultado));

        salvarOperacaoEmCSV("Tangente", String.valueOf(angulo), "", String.valueOf(resultado));

    }//GEN-LAST:event_btTangenteActionPerformed

    private void btCosenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCosenoActionPerformed
        float anguloGraus = Float.parseFloat(tfPrimeiroNumero.getText());
        double anguloRadianos = Math.toRadians(anguloGraus);
        double resultado = Math.cos(anguloRadianos);
        lbResultado.setText(String.valueOf(resultado));

        salvarOperacaoEmCSV("Cosseno", String.valueOf(anguloGraus), "", String.valueOf(resultado));


    }//GEN-LAST:event_btCosenoActionPerformed

    private void btArcoSenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btArcoSenoActionPerformed
        float valorSenoidal = Float.parseFloat(tfPrimeiroNumero.getText());
        if (valorSenoidal < -1 || valorSenoidal > 1) {
            lbResultado.setText("Erro: Valor inválido.");
            return;
        }
        float anguloEmRadianos = (float) Math.asin(valorSenoidal);
        float anguloEmGraus = (float) Math.toDegrees(anguloEmRadianos);
        lbResultado.setText(String.valueOf(anguloEmGraus));

        salvarOperacaoEmCSV("Arcoseno", String.valueOf(valorSenoidal), "", String.valueOf(anguloEmGraus));

    }//GEN-LAST:event_btArcoSenoActionPerformed

    private void btArcoCosenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btArcoCosenoActionPerformed
        float valorSenoidal = Float.parseFloat(tfPrimeiroNumero.getText());
        if (valorSenoidal < -1 || valorSenoidal > 1) {
            lbResultado.setText("Erro: Valor inválido.");
            return;
        }
        float anguloEmRadianos = (float) Math.acos(valorSenoidal);
        float anguloEmGraus = (float) Math.toDegrees(anguloEmRadianos);
        lbResultado.setText(String.valueOf(anguloEmGraus));

        salvarOperacaoEmCSV("Arcocosseno", String.valueOf(valorSenoidal), "", String.valueOf(anguloEmGraus));

    }//GEN-LAST:event_btArcoCosenoActionPerformed

    private void btArcotangenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btArcotangenteActionPerformed
        float valorTangencial = Float.parseFloat(tfPrimeiroNumero.getText());
        float anguloEmRadianos = (float) Math.atan(valorTangencial);
        float anguloEmGraus = (float) Math.toDegrees(anguloEmRadianos);
        lbResultado.setText(String.valueOf(anguloEmGraus));

        salvarOperacaoEmCSV("Arcotangente", String.valueOf(valorTangencial), "", String.valueOf(anguloEmGraus));

    }//GEN-LAST:event_btArcotangenteActionPerformed

    private void btLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogActionPerformed
         float numX = Float.parseFloat(tfPrimeiroNumero.getText());
    float baseY = Float.parseFloat(tfSegundoNumero.getText());
    if (numX <= 0) {
        lbResultado.setText("Erro: O logaritmando (primeiro número) deve ser positivo.");
        salvarOperacaoEmCSV("Logaritmo", String.valueOf(numX), String.valueOf(baseY), "Erro: Logaritmando inválido.");
        return;
    }
    if (baseY <= 0 || baseY == 1) {
        lbResultado.setText("Erro: A base (segundo número) deve ser positiva e diferente de 1.");
        salvarOperacaoEmCSV("Logaritmo", String.valueOf(numX), String.valueOf(baseY), "Erro: Base inválida.");
        return;
    }
    double resultado = Math.log(numX) / Math.log(baseY);
    lbResultado.setText(String.valueOf(resultado));
    salvarOperacaoEmCSV("Logaritmo", String.valueOf(numX), String.valueOf(baseY), String.valueOf(resultado));

    }//GEN-LAST:event_btLogActionPerformed

    private void salvarOperacaoEmCSV(String operacao, String primeiroNumero, String segundoNumero, String resultado) {
        String nomeArquivo = "historico_calculadora.csv";
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        String timestamp = LocalDateTime.now().format(formatter);

        try (FileWriter fw = new FileWriter(nomeArquivo, true); // '
                 PrintWriter pw = new PrintWriter(fw)) {

            pw.println(timestamp + "," + operacao + "," + primeiroNumero + "," + segundoNumero + "," + resultado);
            System.out.println("Operação salva em: " + nomeArquivo);
        } catch (IOException e) {
            System.err.println("Erro ao salvar operação no CSV: " + e.getMessage());

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btArcoCoseno;
    private javax.swing.JButton btArcoSeno;
    private javax.swing.JButton btArcotangente;
    private javax.swing.JButton btCoseno;
    private javax.swing.JButton btDividir;
    private javax.swing.JButton btLog;
    private javax.swing.JButton btMultiplicar;
    private javax.swing.JButton btPercentagem;
    private javax.swing.JButton btPotencia;
    private javax.swing.JButton btRaiz;
    private javax.swing.JButton btSeno;
    private javax.swing.JButton btSomar;
    private javax.swing.JButton btSubtrair;
    private javax.swing.JButton btTangente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbResultado;
    private javax.swing.JTextField tfPrimeiroNumero;
    private javax.swing.JTextField tfSegundoNumero;
    // End of variables declaration//GEN-END:variables
}
